In [8]:

import pandas as pd
import numpy  as np
from sklearn.neighbors import KNeighborsClassifier
from




X_train = np.array([[150, 7], [160, 8], [140, 6], [300, 12], [310, 13], [290, 11]])
y_train = np.array(["Apple", "Apple", "Apple", "Orange", "Orange", "Orange"])


X_test = np.array([[155, 7.5]])

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)


prediction = knn.predict(X_test)

print("predicted fruit:",prediction[0])

predicted fruit: Apple


In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

df = pd.read_csv("Files/knn.csv")



X=df[['sepal_length','sepal_width','petal_length','petal_width']]
Y=df['species']

X_train,X_test,Y_train,Y_test= train_test_split(X,Y,test_size=0.2,random_state=42)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
k = 5
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, Y_train)
Y_pred = knn.predict(X_test)
print("\nConfusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
    


Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
